Update circleci workflow file

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -9,6 +9,7 @@ executors:
 jobs:
   cypress-tests:
     executor: node-executor
+    parallelism: 3 # You can change this number as needed
     steps:
       - checkout
 
@@ -37,10 +38,13 @@ jobs:
             google-chrome --version
 
       - run:
-          name: Run Cypress tests with CPU usage logging
+          name: Run selected Cypress specs with CPU logging
           command: |
             mkdir -p cypress/results
-            /usr/bin/time -v npm run test --browser chrome --reporter mochawesome --reporter-options reportDir=cypress/results 2> cypress/results/cpu_usage.txt || echo "⚠️ Tests failed"
+            TEST_FILES=$(circleci tests glob "cypress/e2e/**/**/*.spec.js" | circleci tests split --split-by=timings)
+            echo "Running test files:"
+            echo "$TEST_FILES"
+            /usr/bin/time -v npx cypress run --browser chrome --reporter mochawesome --reporter-options reportDir=cypress/results,overwrite=false,html=false,json=true --spec "$TEST_FILES" 2> cypress/results/cpu_usage_$(echo $CIRCLE_NODE_INDEX).txt || echo "⚠️ Tests failed"
 
       - run:
           name: Merge Mochawesome report
@@ -49,6 +53,7 @@ jobs:
 
       - run:
           name: Generate HTML report
+          when: always
           command: |
             npx mochawesome-report-generator cypress/results/merged-reports.json --reportDir cypress/results --reportFilename test-report.html
 
